# .goreleaser.yml
version: 2

before:
  hooks:
    - go mod tidy

builds:
  - env:
      - CGO_ENABLED=0
    main: ./main.go
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}}
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - arm64

archives:
  - formats: [tar.gz]
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        formats: [zip]

changelog:
  sort: asc

release:
  github:
    owner: rayomqio
    name: benchmq

brews:
  - name: benchmq
    repository:
      owner: rayomqio
      name: homebrew-tap
    commit_author:
      name: "pyr33x"
      email: "136649231+pyr33x@users.noreply.github.com"
    description: "BenchMQ is a simple, fast, and lightweight CLI to benchmark your MQTT broker with ease"
    homepage: "https://github.com/rayomqio/benchmq"
    license: "Apache-2.0"
    install: |
      bin.install "benchmq"
    test: |
      system "#{bin}/benchmq", "--help"
