name: BenchMQ
version: 1.0.0

environment: development # production
server:
  host: localhost
  port: 1883
client:
  client_id: benchmq-client
  keep_alive: 60
  clean_session: true
  username:
  password:
